---

- name: apply common configs to all the hosts
  hosts: all
  roles:
    - common

- name: setup web hosts
  hosts: web_servers
  roles:
    - php

- name: setup web hosts
  hosts: db_servers
  roles:
    - db
