---
- name: install common tools
  become: true
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - bzip2
    - perl
    - gpg
    - uuid

- name: enable firewalld
  become: true
  systemd:
    name: firewalld
    enabled: yes
    state: started
