# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define("answeb01") do |m|
    m.vm.box = "centos/7"
    m.vm.network "private_network", ip: "192.168.37.10"
    m.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end

  config.vm.define("answeb02") do |m|
    m.vm.box = "centos/7"
    m.vm.network "private_network", ip: "192.168.37.11"
    m.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end

  config.vm.define("ansdb01") do |m|
    m.vm.box = "centos/7"
    m.vm.network "private_network", ip: "192.168.37.12"
    m.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end

  # config.vm.synced_folder "../data", "/vagrant_data"
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL

end
