# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define("webserver") do |m|
    m.vm.box = "centos/7"
    m.vm.network "private_network", ip: "192.168.50.2"
    m.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end

  config.vm.define("dbserver") do |m|
    m.vm.box = "centos/7"
    m.vm.network "private_network", ip: "192.168.50.3"
    m.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end

end
